export async function getAll() {
    return claims;
}

export async function getOne(id) {
    return claims.find((claim) => {
        return claim.id === parseInt(id);
    });
}

const claims = [
  {
      "id": 1,
      "claim_number": "CLM195501",
      "category": "Multiple vehicle",
      "policy_number": "AC-987654321",
      "client_name": "Marty McFly",
      "subject": "Claim for Recent Car Accident - Policy Number: AC-987654321",
      "body": "\n    Dear Parasol Insurance,\n\n    I hope this email finds you well. My name is Marty McFly, and I am writing to file a claim for a recent car accident that occurred on January 2nd, 1955, at approximately 3:30 PM. My policy number is AC-987654321.\n\n    The accident took place at the intersection of Colima Road and Azusa Avenue in the city of Hill Valley. I was driving my vehicle, a silver Delorean DMC-12 with license plate number OUTA-TIME, heading south on Colima Road at approximately 88 mph. At the intersection, the traffic signal was green, and I proceeded through the intersection.\n\n    At the same time, another vehicle, a blue Type 2 Volkswagen Bus with license plate number BIF-RULZ, was traveling west on Azusa Avenue. Unfortunately, the driver failed to stop at the red traffic signal, resulting in a collision with the front passenger side of my vehicle.\n\n    The impact caused significant damage to both vehicles. The front bumper and right headlight of my Delorean are extensively damaged, and the collision cause irreparable damage to the flux capacitor and driver's side gull-wing door mechanism. There are also damages to the front driver's side of the Volkswagen Bus. Fortunately, no injuries were sustained during the accident, and both drivers were able to move their vehicles to the side of the road.\n\n    I promptly exchanged information with the other driver, Mr. Biff Tanner, including our names, phone numbers, insurance details, and a brief description of the accident. Additionally, I took photos of the accident scene, including the damages to both vehicles and the position of the traffic signal.\n\n    I have attached the necessary documents to this email, including the photos, a copy of the police report filed at the Hill Valley Police Department, and the estimate for the repair costs from Hill Valley Auto Repair, where I have taken my vehicle for assessment.\n\n    I kindly request your prompt attention to this matter and would appreciate any guidance on the next steps in the claims process. If you require any additional information or documentation, please do not hesitate to contact me at (916) 555-4385 or marty.mcfly@email.com.\n\n    Thank you for your assistance, and I look forward to a swift resolution of this claim.\n\n    Sincerely,\n\n\n    Marty McFly\n    9303 Lyon Drive\n    Hill Valley, CA 95420\n    (916) 555-4385\n    marty.mcfly@email.com\n    ",
      "summary": "\n    On January 2nd, 1955, at around 3:30 PM, a car accident occurred at the intersection of Colima Road and Azusa Avenue in Hill Vallet. The involved parties were Marty McFly, driving a silver Delorean DMC-12 (OUTA-TIME), and Biff Tanner in a blue Type 2 Volkswagen Bus (BIF-RULZ).\n\n    Marty was heading south on Colima Road when Biff failed to stop at the red traffic signal on Asuza Avenue, causing a collision with Marty's vehicle. Both drivers exchanged information and took photos of the accident scene, which included damages to the front driver and passenger side of Marty's Delorean DMC-12 and the front driver's side of Biff's Volkswagen Bus. No injuries were reported.\n\n    Marty has attached necessary documents, such as photos, a police report, and an estimate for repair costs, to his email. He requests prompt attention to the claim and is available at (916) 555-4385 or marty.mcfly@email.com for any additional information or documentation needed.\n    ",
      "location": "Intersection of Colima Road and Asuza Avenue in the city of Hill Valley",
      "time": "January 2nd, 1955, at approximately 3:30 PM",
      "sentiment": "The sender, Marty McFly, expresses a polite and professional tone in his email. He is respectful and detailed in his description of the car accident and the subsequent steps he took to file a claim. He requests prompt attention to the matter and provides all necessary documentation. Overall, his sentiment is one of being proactive and cooperative in the claims process."
  },
  {
      "id": 2,
      "claim_number": "CLM202402",
      "category": "Multiple vehicle",
      "policy_number": "PT-567890",
      "client_name": "John T. Anderson",
      "subject": "Urgent: Unacceptable Delay and Lack of Communication Regarding Claim #XYZ789",
      "body": "\n    Dear Parasol Insurances,\n\n    I am writing to express my extreme dissatisfaction with the appalling service I have received concerning my recent claim, reference number #XYZ789. The lack of communication and delayed response from your company is utterly unacceptable, and I demand immediate attention to rectify this matter.\n\n    The accident occurred on January 15, 2024, at approximately 3:45 PM, near the intersection of Maple Street and Oak Avenue in Rivertown. My vehicle, a Silver Hawk GT, was struck by another driver, identified as Samantha Reynolds, who ran a red light at the aforementioned intersection. This incident resulted in substantial damage to the front end of my car, including severe structural damage and airbag deployment.\n\n    I reported the claim immediately after the accident, providing all necessary details, witness information, and a detailed description of the events leading up to the collision. However, the response—or lack thereof—from your company has been absolutely deplorable. I have yet to receive any updates on the status of my claim, and my attempts to contact your claims department have been met with prolonged hold times and unhelpful representatives.\n\n    I insist on a thorough investigation into this matter and demand an explanation for the unreasonable delay. It is my right as a policyholder to receive timely updates on the progress of my claim and to be treated with the respect and urgency that this situation demands.\n\n    Furthermore, the lack of transparency and communication from your company is not only unprofessional but also exacerbates the stress and inconvenience caused by the accident itself. I expect immediate action to be taken to expedite the processing of my claim and provide me with the information I am entitled to as a paying customer.\n\n    I am appalled at the disregard for customer satisfaction and the apparent negligence displayed by your company in handling my claim. If my concerns are not addressed promptly and to my satisfaction, I will have no choice but to escalate this matter to the appropriate regulatory authorities and consider legal action.\n\n    I demand a comprehensive update on the status of my claim within the next 48 hours. Failing to meet this deadline will only reinforce my belief that your company values its bottom line over the well-being of its customers.\n\n    I trust that you will treat this matter with the urgency and seriousness it deserves.\n\n    Sincerely,\n    John T. Anderson\n    Policy Number: PT-567890\n    ",
      "summary": "\n    The text is a letter of complaint from John T. Anderson to Parasol Insurances regarding an unresolved car insurance claim, #XYZ789. The incident occurred on January 15, 2024, when Anderson's vehicle was hit by another driver, Samantha Reynolds, who ran a red light. The accident caused significant damage to Anderson's car, and he reported the claim immediately, providing all necessary details. However, he has experienced poor communication and a delayed response from Parasol Insurances. Anderson demands an explanation for the delay, transparency, and urgency in handling his claim. He threatens to escalate the matter to regulatory authorities and consider legal action if his concerns are not addressed promptly. Anderson requests a comprehensive update on the status of his claim within the next 48 hours.\n    ",
      "location": "Near the intersection of Maple Street and Oak Avenue in Rivertown",
      "time": "January 15, 2024, at approximately 3:45 PM",
      "sentiment": "The sender of this claim is expressing extreme dissatisfaction with the handling of their insurance claim by Parasol Insurances. They are frustrated with the lack of communication and the significant delay in processing their claim. The tone of the message is demanding and assertive, with the sender threatening to escalate the matter if their concerns are not addressed promptly."
  },
  {
      "id": 3,
      "claim_number": "CLM502803",
      "category": "Multiple vehicle",
      "policy_number": "AC-987654",
      "client_name": "Jane Doe",
      "subject": "Urgent: Car Accident Claim Assistance Needed",
      "body": "\n    Dear Parasol Inc.,\n\n    I hope this email finds you well. I'm writing to, uh, inform you about, well, something that happened recently. It's, um, about a car accident, and I'm not really sure how to, you know, go about all this. I'm kinda anxious and confused, to be honest.\n\n    So, the accident, uh, occurred on January 15, 2024, at around 3:30 PM. I was driving, or, um, attempting to drive, my car at the intersection of Maple Street and Elm Avenue. It's kinda close to, um, a gas station and a, uh, coffee shop called Brew Haven? I'm not sure if that matters, but, yeah.\n\n    So, I was just, you know, driving along, and suddenly, out of nowhere, another car, a Blue Crest Sedan, crashed into the, uh, driver's side of my car. It was like, whoa, what just happened, you know? There was this screeching noise and, uh, some honking from other cars, and I just felt really, uh, overwhelmed.\n\n    The weather was, um, kinda cloudy that day, but I don't think it was raining. I mean, I can't really remember. Sorry if that's important. Anyway, the road, or, well, maybe the intersection, was kinda busy, with cars going in different directions. I guess that's, you know, a detail you might need?\n\n    As for damages, my car has, uh, significant damage on the driver's side. The front door is all dented, and the side mirror is, like, hanging by a thread. It's not really drivable in its current, uh, state. The Blue Crest Sedan also had some damage, but I'm not exactly sure what because, you know, everything happened so fast.\n\n    I did manage to exchange information with the other driver. Their name is Sarah Johnson, and I got their phone number (555-1234), license plate number (ABC123), and insurance information. So, yeah, I hope that's helpful.\n\n    I'm not sure what, um, steps I should take now. Do I need to go to a specific, uh, repair shop? Should I get a quote for the repairs? And, uh, how do I, you know, proceed with the insurance claim? I'm kinda lost here, and any guidance or assistance you can provide would be really, um, appreciated.\n\n    Sorry if this email is a bit all over the place. I'm just really, uh, anxious about the whole situation. Thank you for your understanding.\n\n    Sincerely,\n\n    Jane Doe\n    Policy Number: AC-987654\n    ",
      "summary": "",
      "location": "",
      "time": "",
      "sentiment": ""
  },
  {
      "id": 4,
      "claim_number": "CLM202415",
      "category": "Single vehicle",
      "policy_number": "BK-5165426",
      "client_name": "Dominic Toretto",
      "subject": "Claim for Car Accident - Policy #: BK-5165426",
      "body": "\n    Dear Parasol Insurance Team,\n\n    I hope this email finds you well. I'm reaching out to file a claim regarding a recent incident involving my car, which is covered under my policy with Parasol. The accident occurred last night on the streets of Los Angeles, and I wanted to provide you with all the necessary details.\n\n    Location: The accident took place at the intersection of Sunset Boulevard and Vine Street in downtown Los Angeles. It was one of those crazy nights, where the streets were alive with the sound of engines and the glow of neon lights.\n\n    Circumstances: So, here's the deal. I was out cruising with the crew, enjoying the vibe of the city, when suddenly we found ourselves in the middle of a high-speed chase. There was this dude, let's call him Johnny Tran for the sake of this email, who thought he could outmaneuver us. Little did he know, we don't play by the rules.\n\n    Anyway, Johnny pulled some slick moves, cutting through traffic like a bat outta hell. Naturally, being the king of the streets that I am, I had to show him what real speed looks like. So, I hit the nitrous and went full throttle.\n\n    But then, outta nowhere, this semi-truck decided to make a left turn without signaling. I had to make a split-second decision, and I ended up launching my car off a ramp, trying to clear the truck like we're in one of those crazy action flicks. It was like something straight outta the movies, I tell ya.\n\n    Long story short, the stunt didn't exactly go as planned. My car ended up crashing into a billboard, flipping over a couple of times before finally coming to a stop. Yeah, it was a total wreck. But hey, at least we walked away without a scratch, just a little shaken, not stirred, if you catch my drift.\n\n    Damage: As for the damage to my car, let's just say it's gonna need more than a few wrenches and some duct tape to fix this baby up. The front end is smashed in, the windows are shattered, and I'm pretty sure the chassis is twisted beyond recognition. It's gonna take a miracle to get her back on the road.\n\n    I understand that accidents happen, but I'm counting on Parasol to have my back in times like these. I've been a loyal customer for years, and I trust that you'll handle my claim with the same speed and precision that I handle my rides.\n\n    Please let me know what steps I need to take to get the ball rolling on this claim. I'm ready to do whatever it takes to get my car back in top shape and back on the streets where it belongs.\n\n    Looking forward to hearing from you soon.\n\n    Sincerely,\n    Dominic Toretto\n    ",
      "summary": "The email is from a customer named Dominic Toretto, requesting to file a claim for a car accident that occurred in Los Angeles. He describes the incident as involving a high-speed chase with another driver named Johnny Tran, who cut through traffic and caused Dominic to take evasive action. Dominic attempted to clear the truck by launching his car off a ramp but ended up crashing into a billboard, causing significant damage to the front end, shattered windows, and possibly a twisted chassis. The sender expresses confidence in Parasol's ability to handle the claim efficiently due to their long-term loyalty as a customer. They ask for guidance on the next steps to take in the claims process.",
      "location": "The event the claim is related to happened at the intersection of Sunset Boulevard and Vine Street in downtown Los Angeles.",
      "time": "The event described in the claim text occurred last night (no specific date mentioned) at an intersection in downtown Los Angeles, specifically at Sunset Boulevard and Vine Street. The exact time is not provided in the text.",
      "sentiment": "The person sending the claim, identified as Dominic Toretto, expresses a positive sentiment towards Parasol Insurance and his expectation of them handling his claim efficiently. However, the tone of the email is also boastful and exaggerated, describing an unlikely series of events involving a car accident and a high-speed chase. Despite the unconventional circumstances, Dominic expresses confidence in Parasol's ability to help him get his car repaired."
  },
  {
      "id": 5,
      "claim_number": "CLM52125",
      "category": "Multiple vehicle",
      "policy_number": "AC-418324",
      "client_name": "Saul Goodman",
      "subject": "Where is My Money? Urgent Attention Needed for My Car Accident Claim",
      "body": "\n    Dear Stoneheart Insurance Claims Department,\n\n    I am absolutely *thrilled* (read: infuriated) to be writing yet another heartfelt missive to the void that is your customer service. My recent car accident claim has vanished into the ether, much like my patience and the professionalism I expected from your company. How about we resolve this before the next ice age?\n\n    Let's recap the blockbuster event:\n    On March 28, 2023, at around 4:15 PM, at the intersection of 5th Avenue and Main St in Springfield, my car was passionately sideswiped by another vehicle. Why? Because the other driver blasted through a red light and T-boned my car's passenger side. It was a harrowing scene, made worse by your glacial pace of response.\n\n    It's been over two weeks, and your commitment to delay is almost impressive. I demand a comprehensive review and prompt update on my claim within the next 24 hours. This isn't just a request—it's a necessity driven by sheer frustration and the urgent need for resolution.\n\n    Please treat this matter with the urgency it clearly deserves. I expect a detailed plan of action and a swift response, or be assured, further actions including legal recourse will be considered.\n\n    Looking forward to an expedited resolution,\n    Saul Goodman\n\n    CC: My 17 Twitter Followers\n\n    Attach: Police Report No. 12345, Photos of the Incident, Documented Calls and Emails\n    ",
      "summary": "The text is a letter from a customer named Saul Goodman to the Stoneheart Insurance Claims Department regarding an unresolved car accident claim. The incident occurred on March 28, 2023, at the intersection of 5th Avenue and Main St in Springfield, where Saul's car was hit by another vehicle that ran a red light. He is frustrated with the lack of progress on his claim, which has been ongoing for over two weeks. Saul demands a thorough review and update within 24 hours, threatening further actions if his request is not met. He attaches relevant documents, including a police report, photos of the incident, and records of calls and emails, to support his claim.",
      "location": "The event the claim is related to happened at the intersection of 5th Avenue and Main St in Springfield.",
      "time": "The car accident described in the text occurred on March 28, 2023, at around 4:15 PM.",
      "sentiment": "The sentiment of the person sending this claim is one of frustration and urgency. They are expressing dissatisfaction with the delay in processing their car accident claim and threatening further action if it is not resolved promptly."
  },
  {
      "id": 6,
      "claim_number": "CLM605208",
      "category": "Multiple vehicle",
      "policy_number": "AC-768901",
      "client_name": "Tyrion Lannister",
      "subject": "Urgent Claim Review Required: Collision in King's Landing",
      "body": "\n    Dear Westeros Insurance Claims Department,\n\n    This correspondence is from Tyrion Lannister, currently not in a tavern but rather dealing with the aftermath of an unpleasant vehicular incident. As a man known for resolving conflicts, I find myself ironically embroiled in one that requires your immediate attention.\n\n    Here are the distressing details:\n    On April 15, 2023, at about noon, within the confines of King's Landing, my car was struck by another. As I navigated through the bustling streets near the marketplace, a distracted driver—likely admiring the view of the Blackwater Bay instead of the road—rammed into my car's side. This not only caused significant damage to the vehicle but also disrupted my travel plans significantly.\n\n    Nearly a month has elapsed since the accident, and yet, I've seen more action in the Small Council meetings than in the progress of my claim. Your lack of promptness in handling this matter is both noted and distressing. I require an exhaustive review and a swift update on my claim within the next 48 hours. This is not a mere request, but a necessity fueled by urgent needs and dwindling patience.\n\n    Please address this claim with the seriousness it merits. I expect a detailed response and a rapid resolution, or rest assured, further actions, potentially involving the Crown, will be considered.\n\n    I await your expedited action,\n    Tyrion Lannister\n\n    CC: Master of Coin\n\n    Attach: Car Damage Photos, Eyewitness Accounts, Incident Report No. KL509\n    ",
      "summary": "",
      "location": "",
      "time": "",
      "sentiment": ""
  }
]